name: Build Chrome Extension

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

# 添加permissions配置，确保工作流有适当的权限
permissions:
  contents: write  # 需要写入权限来创建releases
  packages: read
  issues: read
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Build Extension Package
        run: |
          cd extension
          zip -r ../any2md-extension.zip ./*
      
      - name: Upload Extension Artifact
        uses: actions/upload-artifact@v4
        with:
          name: any2md-extension
          path: any2md-extension.zip
      
      # 仅在标签推送时创建Release
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: any2md-extension.zip
          draft: false
          prerelease: false
          generate_release_notes: true
        # 已通过permissions块配置了适当的权限 